"use client";
import { ChangeEvent, useMemo, useState } from "react";
import mammoth from "mammoth";
import * as pako from "pako";

type StageId="unassigned"|"overview"|"campaign"|"early-maps"|"low-budget"|"medium-budget"|"high-budget"|"endgame";
type Section={id:string;title:string;content:string;selected:boolean;stageId:StageId};
type PobSet={id:string;name:string;stageId:StageId;entries:string[]};
type PobResult={notes:string;trees:PobSet[];skills:PobSet[];items:PobSet[]};
const stages:Array<[StageId,string]>=[["unassigned","尚未分類"],["overview","總覽"],["campaign","劇情"],["early-maps","初入輿圖"],["low-budget","低預算"],["medium-budget","中預算"],["high-budget","高預算"],["endgame","終局"]];
const uid=()=>Math.random().toString(36).slice(2,9);
const inferStage=(text:string):StageId=>{const v=text.toLowerCase();if(/act|campaign|leveling|劇情|章節/.test(v))return"campaign";if(/early|start|初入|開荒/.test(v))return"early-maps";if(/low|低預算/.test(v))return"low-budget";if(/mid|medium|中預算/.test(v))return"medium-budget";if(/high|高預算/.test(v))return"high-budget";if(/late|endgame|uber|終局|svalinn/.test(v))return"endgame";if(/overview|summary|總覽|摘要/.test(v))return"overview";return"unassigned"};
const heading=/^(summary|overview|skills?|passives?|ascendancy|pantheon|gearing|equipment|crafting|faq|frequently asked|mechanics?|playstyle|bossing|mapping|leveling|act\s*\d|early|mid|late|low budget|medium budget|high budget|endgame|總覽|摘要|技能|天賦|昇華|眾神殿|裝備|製作|常見問題|機制|操作|打王|劇情|初入輿圖|低預算|中預算|高預算|終局)/i;
const splitSections=(raw:string):Section[]=>{const lines=raw.replace(/\r/g,"").split("\n").map(x=>x.trim()).filter(Boolean);const out:Section[]=[];let title="未分類內容",body:string[]=[];const flush=()=>{if(body.length)out.push({id:uid(),title,content:body.join("\n"),selected:true,stageId:inferStage(title)});body=[]};for(const line of lines){const h=heading.test(line)||(line.length<=55&&!/[。；;,.，]$/.test(line)&&/:$/.test(line));if(h){flush();title=line.replace(/:$/,"")}else body.push(line)}flush();return out.length?out:[{id:uid(),title:"全文",content:raw,selected:true,stageId:"unassigned"}]};
const decodePob=(code:string):PobResult=>{const clean=code.trim().replace(/\s/g,"").replace(/-/g,"+").replace(/_/g,"/");const binary=atob(clean+"=".repeat((4-clean.length%4)%4));const bytes=Uint8Array.from(binary,c=>c.charCodeAt(0));const inflated=pako.inflate(bytes);const xml=new TextDecoder("utf-8").decode(inflated).replace(/^\uFEFF/,"").replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/g,"");const doc=new DOMParser().parseFromString(xml,"application/xml");const parserError=doc.querySelector("parsererror");if(parserError)throw new Error(`PoB XML 無法解析：${(parserError.textContent||"未知 XML 錯誤").replace(/\s+/g," ").slice(0,180)}`);const nameOf=(el:Element,i:number,p:string)=>el.getAttribute("title")||el.getAttribute("name")||el.getAttribute("label")||`${p} ${i+1}`;const trees=Array.from(doc.querySelectorAll("Tree > Spec")).map((el,i)=>{const name=nameOf(el,i,"天賦組");return{id:uid(),name,stageId:inferStage(name),entries:[`天賦節點：${(el.getAttribute("nodes")||"").split(",").filter(Boolean).length}`,el.getAttribute("treeVersion")?`版本：${el.getAttribute("treeVersion")}`:""].filter(Boolean)}});const sr=Array.from(doc.querySelectorAll("Skills > SkillSet"));const skills=(sr.length?sr:Array.from(doc.querySelectorAll("Skills")).slice(0,1)).map((el,i)=>{const name=nameOf(el,i,"技能組");const entries=Array.from(el.querySelectorAll("Skill")).map(s=>{const gems=Array.from(s.querySelectorAll("Gem")).filter(g=>g.getAttribute("enabled")!=="false").map(g=>g.getAttribute("nameSpec")||g.getAttribute("skillId")).filter(Boolean);return`${s.getAttribute("slot")||s.getAttribute("label")||"未指定裝備"}：${gems.join(" → ")}`}).filter(x=>!x.endsWith("："));return{id:uid(),name,stageId:inferStage(name),entries}});const itemText=new Map(Array.from(doc.querySelectorAll("Items > Item")).map(el=>[el.getAttribute("id")||"",(el.textContent||"").trim()]));const ir=Array.from(doc.querySelectorAll("Items > ItemSet"));const items=(ir.length?ir:Array.from(doc.querySelectorAll("Items")).slice(0,1)).map((el,i)=>{const name=nameOf(el,i,"裝備組");const entries=Array.from(el.querySelectorAll("Slot")).map(s=>{const raw=itemText.get(s.getAttribute("itemId")||"")||"";return`${s.getAttribute("name")||"裝備"}：${raw.split("\n").slice(0,2).join(" — ")||"未配置"}`});return{id:uid(),name,stageId:inferStage(name),entries}});return{notes:doc.querySelector("Notes")?.textContent?.trim()||"",trees,skills,items}};

export default function ConverterWorkbench({open,onClose}:{open:boolean;onClose:()=>void}){const[sourceUrl,setSourceUrl]=useState("");const[files,setFiles]=useState<Array<{name:string;type:string;size:number;sha256:string}>>([]);const[sections,setSections]=useState<Section[]>([]);const[pobCode,setPobCode]=useState("");const[pob,setPob]=useState<PobResult|null>(null);const[status,setStatus]=useState("等待資料");const selectedCount=useMemo(()=>sections.filter(x=>x.selected).length,[sections]);if(!open)return null;
const hash=async(b:ArrayBuffer)=>Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",b))).map(x=>x.toString(16).padStart(2,"0")).join("");
const loadFiles=async(e:ChangeEvent<HTMLInputElement>)=>{const picked=Array.from(e.target.files||[]);if(!picked.length)return;setStatus("正在解析文件…");try{const next:Section[]=[],metas=[];for(const file of picked){const buffer=await file.arrayBuffer();metas.push({name:file.name,type:file.type,size:file.size,sha256:await hash(buffer)});const text=file.name.toLowerCase().endsWith(".docx")?(await mammoth.extractRawText({arrayBuffer:buffer})).value:await file.text();next.push(...splitSections(text).map(s=>({...s,title:`${file.name}｜${s.title}`})))}setFiles(old=>[...old,...metas]);setSections(old=>[...old,...next]);setStatus(`完成：找到 ${next.length} 個段落`)}catch(error){setStatus(`解析失敗：${error instanceof Error?error.message:"未知錯誤"}`)}e.target.value=""};
const parsePob=()=>{try{setPob(decodePob(pobCode));setStatus("PoB 解析完成，請確認各組階段")}catch(error){setStatus(`PoB 解析失敗：${error instanceof Error?error.message:"請確認匯出碼"}`)}};const patchSection=(sid:string,patch:Partial<Section>)=>setSections(xs=>xs.map(x=>x.id===sid?{...x,...patch}:x));const patchSet=(kind:"trees"|"skills"|"items",sid:string,stageId:StageId)=>setPob(c=>c?{...c,[kind]:c[kind].map(x=>x.id===sid?{...x,stageId}:x)}:c);
const download=()=>{const bundle={format:"poe-source-bundle-v1",createdAt:new Date().toISOString(),source:{url:sourceUrl,files},sections:sections.filter(x=>x.selected).map(({id:_,...x})=>x),pob:pob?{...pob,rawCode:pobCode}:null,processingNotes:["階段由名稱初判；尚未分類項目需人工確認。","來源包不會覆蓋攻略庫。"]};const blob=new Blob([JSON.stringify(bundle,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`poe-source-bundle-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url)};
const renderSets=(title:string,kind:"trees"|"skills"|"items",sets:PobSet[])=><section className="converter-block"><h3>{title}<span>{sets.length}</span></h3>{sets.length?sets.map(set=><details key={set.id}><summary>{set.name}<select value={set.stageId} onClick={e=>e.stopPropagation()} onChange={e=>patchSet(kind,set.id,e.target.value as StageId)}>{stages.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></summary><ul>{set.entries.map((x,i)=><li key={i}>{x}</li>)}</ul></details>):<p className="converter-empty">尚無資料</p>}</section>;
return <div className="modal-backdrop converter-backdrop"><section className="modal converter-modal"><div className="modal-head"><div><small>GUIDE CONVERSION WORKBENCH</small><h2>攻略轉換工作台</h2></div><button onClick={onClose}>×</button></div><p className="converter-lead">先把來源文件與 PoB 解析成可重複使用的來源包，以後不必每次重讀整份 Word。</p><div className="converter-inputs"><label>攻略來源網址<input value={sourceUrl} onChange={e=>setSourceUrl(e.target.value)} placeholder="Maxroll、Mobalytics、影片或原作者頁面"/></label><label className="file-drop">上傳 Word／TXT／JSON<input type="file" multiple accept=".docx,.txt,.json" onChange={loadFiles}/><span>選擇檔案</span></label></div><section className="converter-block"><h3>PoB 匯出碼</h3><textarea value={pobCode} onChange={e=>setPobCode(e.target.value)} placeholder="貼上 Path of Building 匯出字串…"/><button className="primary" disabled={!pobCode.trim()} onClick={parsePob}>解析 PoB</button></section><div className="converter-status">{status}</div>
{sections.length>0&&<section className="converter-block"><h3>文件段落 <span>{selectedCount}/{sections.length}</span></h3><p className="converter-hint">取消頁首頁尾與重複內容；標題和階段都能修正。</p><div className="section-review">{sections.map(s=><div key={s.id} className={s.selected?"source-section":"source-section disabled"}><input type="checkbox" checked={s.selected} onChange={e=>patchSection(s.id,{selected:e.target.checked})}/><input value={s.title} onChange={e=>patchSection(s.id,{title:e.target.value})}/><select value={s.stageId} onChange={e=>patchSection(s.id,{stageId:e.target.value as StageId})}>{stages.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><details><summary>預覽</summary><pre>{s.content.slice(0,1800)}{s.content.length>1800?"\n…":""}</pre></details></div>)}</div></section>}
{pob&&<><div className="converter-grid">{renderSets("天賦組","trees",pob.trees)}{renderSets("技能組（依裝備）","skills",pob.skills)}{renderSets("裝備組","items",pob.items)}</div><section className="converter-block"><h3>PoB Notes</h3><pre className="notes-preview">{pob.notes||"作者沒有填寫 Notes。"}</pre></section></>}
<footer className="converter-footer"><div><strong>輸出不會直接改寫攻略庫</strong><span>保存來源包後，再由 AI 或人工轉成 v3 攻略。</span></div><button className="primary" disabled={!sections.length&&!pob} onClick={download}>匯出來源包 JSON</button></footer></section></div>}
